all:
  hosts:
    oss-cor:
      ansible_host: 10.220.100.13
  children:
    db:
      hosts:
        oss-db1:
          ansible_host: 10.220.100.11
          postgresql_role: primary
        oss-db2:
          ansible_host: 10.220.100.12
          postgresql_role: standby
